### ISSUE TITLE
NPM install calling plugman.fetch, overwrites custom config parameters

### ISSUE THREAD

**Issue by johnkcox** [xmartlabs/cordova-plugin-market#11]
Thanks for creating this plugin. When we include it in our project's config.xml like so:

```
<plugin name="cordova-plugin-market" spec="~1.1.0" />
```

for some reason it installs itself using `plugman.fetch` during the `$cordova prepare ios` phase. the result is that custom configuration settings in the `*-Info.plist` are getting overwritten. we changed the line in our config.xml to install your plugin from git as so:

```
<plugin name="com.xmartlabs.cordova.market" spec="https://github.com/xmartlabs/cordova-plugin-market" />
```

and the problem goes away. is there something unusual about how we added it the first time, or is this something in your set up?

thanks again for making this plugin!

**Comment by djett41** [comment]
@johnkcox I believe this is because in his plugin.xml the id is com.xmartlabs.cordova.market when the npm id cordova-plugin-market, I believe the Cordova CLI recognizes it as a different plugin since the config.xml plugin name, and the id are different.

If they update their plugin id to be cordova-plugin-market this annoying reinstall attempt should go away.. With that being said, probably safer to live the the reinstall attempt than to grab the latest from master.

**Comment by doppelganger9** [comment]
I also had problem with the mismatch between the plugin.xml id and the package.json name.
It occured when doing `cordova prepare ios`.
The linked PR solves this.

**Comment by m-revetria** [comment]
PR #16 was recently merged. This issue should be solved now.

Thanks to all for the contributions.
